---
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install Managed Lustre Client Repo
  ansible.builtin.yum_repository:
    name: "lustre-client-rocky-{{ ansible_distribution_major_version }}"
    description: "Lustre Client"
    baseurl: '{{ managed_lustre_repo_url }}'
    enabled: true
    gpgcheck: false
  become: yes

- name: Install Lustre Client with DKMS support
  ansible.builtin.dnf:
    name: "{{ managed_lustre_packages + ['kernel-devel-' + ansible_kernel, 'kernel-headers-' + ansible_kernel, 'gcc', 'make', 'elfutils-libelf-devel'] }}"
    exclude:
      - kmod-lustre-client
    state: present
    update_cache: true
  register: lustre_install
  become: yes

- name: Force a DKMS build/install for Lustre
  ansible.builtin.command:
    cmd: dkms autoinstall
  when: lustre_install.changed
  become: yes

